name = "Spectral Seas"
author = "Kevin Murphy"
version = "0.9.11-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ab1919cea790b26278e1de9df7b3465804e41ff795e3bc62a4c7ba4ceecf6be"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2", "1.19.4", "1.20.4"]
datapack-folder = "config/paxi/datapacks"
