name = "Spectral Seas"
author = "Kevin Murphy"
version = "0.9.11-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2689cecbb12311eb2a9bf76c77cd2574b98a5045c32ea58d2783866f4ea7e8a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2", "1.19.4", "1.20.4"]
datapack-folder = "config/paxi/datapacks"
