[general]
	#Chance of XP dropping on harvest.
	#Range: 0 ~ 100
	xpFromHarvestChance = 0
	#List of individual hoe tools and their harvest tier. This is for modded items not covered.
	#Format: minecraft:wooden_hoe-0 (with number being tier)
	hoeItems = []
	#Amount of XP dropped on harvest.
	#Range: 0 ~ 10
	xpFromHarvestAmount = 1
	#Regular hoe (gold, wood, iron) expansion range.
	#Range: 1 ~ 5
	highTierExpansionRange = 3
	#Harvestable crops.
	#Format: "harvestState[,afterHarvest]", i.e. "minecraft:wheat[age=7]"
	#or "minecraft:cocoa[age=2,facing=north],minecraft:cocoa[age=0,facing=north]"
	#WARNING: If autoConfigMods is set to false, only crops defined here will work.
	#If not, it will just add to the auto-configured list.
	harvestableCrops = []
	#Allow harvesting with empty hand. If disabled, requires hoe.
	allowEmptyHand = false
	#Automatically register crops.
	autoConfigMods = true
	#Expand hoe range based on tier.
	expandHoeRange = false
	#Harvesting crops costs durability.
	damageTool = true
	#Regular hoe (gold, wood, iron) expansion range.
	#Range: 1 ~ 5
	smallTierExpansionRange = 2
	#Allow machines, like Create's deployer, to harvest crops.
	allowFakePlayer = true
	#Expand hoe range by 1 for each level of efficiency enchantment level.
	expandHoeRangeEnchanted = true
	#Range of XP dropped on harvest. Format: "min-max", example: "0-3"
	xpFromHarvestRangeAmount = "0-3"
	#List of crops to blacklist from right-click harvest. Format: "modid:block"
	blacklistCrops = []
	#List of mods to blacklist from right-click harvest. Format: "modid"
	blacklistMods = []
	#Use range for XP drop, instead of set amount.
	xpFromHarvestUseRange = false
	#Maximum range hoe can expand for harvesting.
	#This is the maximum of tier + efficiency enchantment.
	#Range: 1 ~ 11
	maxHoeExpansionRange = 11
	#List of held items to blacklist from right-click harvest. Format: "modid:item"
	blacklistHeldItems = []
	#Blocks that right clicking should simulate click instead of breaking.
	#For blocks like berry bushes that have built-in right click harvest.
	harvestableBlocks = ["minecraft:sweet_berry_bush", "minecraft:cave_vines"]
